### ISSUE TITLE
Remote code execution

### ISSUE THREAD

**Issue by ponguruswamy** [adrienjoly/npm-pdfreader#100]
Lodash is vulnerable to remote code execution (RCE) due to the potential to modify the properties of objects in memory. A remote attacker could run arbitrary commands on a vulnerable server, or cause the server to crash, by maliciously crafting an object via the zip functionality of Lodash.

**Comment by adrienjoly** [comment]
Hi ponguruswamy, thanks for the heads up!

Would you be interested in submitting a Pull Request to fix this?

**Comment by adrienjoly** [comment]
FYI, since we upgraded dependencies (https://github.com/adrienjoly/npm-pdfreader/commit/3dcd291364237b2170e93830331eadef8fe65a50), Dependabot does not report any vulnerability anymore:

![image](https://user-images.githubusercontent.com/531781/160558869-863d8a15-18ed-45e8-9ca6-ed40c67c4082.png)

=> Closing this issue.
