### ISSUE TITLE
trouble parsing files created by wkhtmltopdf

### ISSUE THREAD

**Issue by zorla** [adrienjoly/npm-pdfreader#2]
hi adrien

created a pdf file from your sample.html by wkhtmltopdf.
unfortunately i can not parse it proberly with your test.js.
just log item.text. 

problem is, i have to parse generated files.
generated file is attached.

do you have any clue?

thanks in advance.

greets 
zorla

[sample3.pdf](https://github.com/adrienjoly/npm-pdfreader/files/45164/sample3.pdf)

**Comment by adrienjoly** [comment]
Hi Zorla,

Thanks for your detailed ticket. I'll have a look at it on Sunday.

Enjoy your weekend!

Adrien

On Thu, Nov 26, 2015 at 6:33 PM zorla <notifications@github.com> wrote:

> hi adrien
>
> created a pdf file from your sample.html by wkhtmltopdf.
> unfortunately i can not parse it proberly with your test.js.
> just log item.text.
>
> problem is, i have to parse generated files.
> generated file is attached.
>
> do you have any clue?
>
> thanks in advance.
>
> greets
> zorla
>
> sample3.pdf
> <https://github.com/adrienjoly/npm-pdfreader/files/45164/sample3.pdf>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adrienjoly/npm-pdfreader/issues/2>.
>
-- 
Adrien Joly
adrienjoly.com

**Comment by adrienjoly** [comment]
Hi @zorla,

I ran `npm test` with your version of sample.pdf, and it does not work, indeed.

The reason is straightforward, though: in your version of the PDF file, text strings are stored character by character (1 character = 1 pdf item => 1 word = several items => ['H', 'e', 'l', 'l', 'o']), whereas in the provided version: characters are grouped into text strings (1 word = 1 item => 'Hello').

If you compare the outputs of 'npm test' with the original `/test/sample.pdf`, then yours, you'll understand the difference, and the complexity it brings to the parsing process. For that reason, npm-pdfreader does not support files that are splitted that way.

If you want to fork the project and add support for this kind of file, please feel free to do so, and make sure to pull request.

Best regards,

Adrien

**Comment by zorla** [comment]
Hi @adrien,

thank you for your support.

So, first i have to check, why pdf2json parses each character as group items.
Will see, if there is a proper solution.

Cheers
Zorla

**Comment by adrienjoly** [comment]
Alright, please let me now of your progress!

Cheers,

Adrien

On Tue, Dec 1, 2015, 11:37 AM zorla <notifications@github.com> wrote:

> Hi @adrien <https://github.com/adrien>,
>
> thank you for your support.
>
> So, first i have to check, why pdf2json parses each character as group
> items.
> Will see, if there is a proper solution.
>
> Cheers
>
>
> Zorla
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adrienjoly/npm-pdfreader/issues/2#issuecomment-160929585>
> .
>
-- 
Adrien Joly
adrienjoly.com

**Comment by adrienjoly** [comment]
@zorla FYI, I just published an example of row-based parsing in README.md. This could help aggregate the characters back together.
