### ISSUE TITLE
Pdfreader cannot be used with Electron (because of `async` variable in pdf2json)

### ISSUE THREAD

**Issue by paul321** [adrienjoly/npm-pdfreader#23]
We wanted to test the library in Electron but it doesn't import properly the async library, pdfparser.js line 6:

    async = require("async");

As you may know async is a reserved word in Chrome and you guys are trying to import async library by overwriting the async reserved word without var or let in front of the async var.

**Comment by adrienjoly** [comment]
Hi Paul, thanks for your message!

`async` is not only a reserved word in Chrome, it was introduced in the JavaScript langage since [ES2017](http://www.ecma-international.org/ecma-262/8.0/index.html#prod-FunctionDeclaration), I believe. So, you're right, we should give another name to that symbol in order to prevent conflicts.

Would you like to make that change and propose a Pull Request to this repository? If so, don't hesitate to ask me for assistance if needed.

**Comment by adrienjoly** [comment]
Actually, I did not find any mention of `async` in the code of `pdfreader` (this package), and `pdfparser.js` seems to come from the `pdf2json` dependency.

**Comment by adrienjoly** [comment]
Unfortunately, even the latest version of the `pdf2json` dependency uses `async` as variable name: https://github.com/modesty/pdf2json/blob/master/pdfparser.js...

=> As that dependency does not seem to be actively maintained, my suggestion would be that you create a fork of `pdf2json` that renames that variable in order to prevent the conflict, and then propose a PR to `pdfreader` (this package) to use your fork of `pdf2json`.

Or do you have another idea of solution?

**Comment by adrienjoly** [comment]
Erratum: there were some updates on pdf2json, recently.

Feel free to report any issues or make requests directly on their repository.

Closing.
