### ISSUE TITLE
Async reading

### ISSUE THREAD

**Issue by Michaeladze** [adrienjoly/npm-pdfreader#24]
I am using nodejs express server. On GET request I expect to receive read PDF file. But reading is async process. 
`new pdfreader.PdfReader().parseFileItems('CHK.pdf', function (err, item) {
       
 if (!item || item.page) {
            res.send(printRows());
        }
    });`

Is there any way to wait, until all the pages will be read and only then send response back to client?

**Comment by adrienjoly** [comment]
Hi Michael,

If I understand well, you would like your GET request handler to return a response *after* the PDF file was fully received and parsed.

In the code you provide, I see that:
- a response will be sent whenever the parsing is done (i.e. the `!item` part of your condition, because `item` will be `null` at that stage)
- a response would also be sent for every page (i.e. the `item.page` page of your condition)

So I'm guessing that you may want to drop the `item.page` part of your condition.

You'll find more explanations about the different values `item` can have in https://github.com/adrienjoly/npm-pdfreader#raw-pdf-reading.

Also, make sure that your `CHK.pdf` file was fully stored before loading it with `parseFileItems()`. 

Hope this helps!

**Comment by adrienjoly** [comment]
No news => closing.
