### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by childmoon** [adrienjoly/npm-pdfreader#96]
code：
new pdfreader.PdfReader().parseFileItems(
            fileAllname,
            function (err, item) {
                if(item&&item.page){
                    item5.allpage=item.page
                } else if (item.text) {
                   initlist.push(item.text)
                }
}
console.log(initlist)
----------------------------
I assign a value to my custom data in the function of parsing pdf, and then output it. It is found that the data is still the initial value. How should I deal with the processed data?

**Comment by adrienjoly** [comment]
It's complicated to help without more context, but you should at least handle errors (i.e. the `err` parameter) like it's done in the following example: https://github.com/adrienjoly/npm-pdfreader#raw-pdf-reading

Also, please keep in mind that parsing a file is an asynchronous process, so `initlist` is probably not gonna be fully set if you use it right after calling `parseFileItems()`.

In order to know when the parsing is done, check if `item` is `null`, like it's done in the example provided above.
