### ISSUE TITLE
modifying properties of Obj

### ISSUE THREAD

**Issue by ponguruswamy** [adrienjoly/npm-pdfreader#99]
Minimist is a parse argument options module. Affected versions of this package are vulnerable to Prototype Pollution. The library could be tricked into adding or modifying properties of Object

Xmldom is used as  parser and xml serializer.The library could  be tricked into adding or modifying the xml

**Comment by adrienjoly** [comment]
Hi ponguruswamy, thanks for the heads up!

Would you be interested in submitting a Pull Request to fix this?

**Comment by adrienjoly** [comment]
FYI, since we upgraded dependencies (https://github.com/adrienjoly/npm-pdfreader/commit/3dcd291364237b2170e93830331eadef8fe65a50), Dependabot does not report any vulnerability anymore:

![image](https://user-images.githubusercontent.com/531781/160558869-863d8a15-18ed-45e8-9ca6-ed40c67c4082.png)

=> Closing this issue.
